2025-06-22 15:55:19,001 p=45768 u=bill n=ansible INFO| fatal: [desktop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.40\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.40 port 22: No route to host\r\n", "unreachable": true}
2025-06-22 15:55:19,069 p=45768 u=bill n=ansible INFO| fatal: [dell]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.55\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.55 port 22: No route to host\r\n", "unreachable": true}
2025-06-22 15:55:23,027 p=45768 u=bill n=ansible INFO| fatal: [lily_laptop]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.86.53\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.86.53 port 22: No route to host\r\n", "unreachable": true}
2025-06-22 15:57:26,947 p=45768 u=bill n=ansible INFO| fatal: [samsung]: FAILED! => {"changed": false, "cmd": "['classic', 'channel', 'state', 'firefox']", "msg": "Ooops! Snap operation failed while executing '['classic', 'channel', 'state', 'firefox']', please examine logs and error output for more details.", "output": {"cmd": "['classic', 'channel', 'state', 'firefox']", "snaps_removed": ["firefox"], "version": {"kernel": "6.11.0-26-generic", "series": "16", "snap": "2.68.5", "snapd": "2.68.5", "ubuntu": "24.04"}}, "snaps_removed": ["firefox"], "vars": {"cmd": "['classic', 'channel', 'state', 'firefox']", "snaps_removed": ["firefox"], "version": {"kernel": "6.11.0-26-generic", "series": "16", "snap": "2.68.5", "snapd": "2.68.5", "ubuntu": "24.04"}}, "version": {"kernel": "6.11.0-26-generic", "series": "16", "snap": "2.68.5", "snapd": "2.68.5", "ubuntu": "24.04"}}
2025-06-22 15:57:50,815 p=45768 u=bill n=ansible INFO| fatal: [samsung]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 47, in invoke_module\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_apt_repository_payload_ykacfx06/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py\", line 782, in <module>\n  File \"/tmp/ansible_apt_repository_payload_ykacfx06/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py\", line 748, in main\n  File \"/usr/lib/python3/dist-packages/apt/cache.py\", line 157, in __init__\n    self.open(progress)\n  File \"/usr/lib/python3/dist-packages/apt/cache.py\", line 214, in open\n    self._cache = apt_pkg.Cache(progress)\n                  ^^^^^^^^^^^^^^^^^^^^^^^\napt_pkg.Error: E:Conflicting values set for option Signed-By regarding source https://packages.microsoft.com/repos/code/ stable: /etc/apt/keyrings/packages.microsoft.gpg != /usr/share/keyrings/microsoft.gpg, E:The list of sources could not be read.\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1}
2025-06-22 15:57:51,065 p=45768 u=bill n=ansible INFO| fatal: [samsung]: FAILED! => {"changed": false, "msg": "E:Conflicting values set for option Signed-By regarding source https://packages.microsoft.com/repos/code/ stable: /etc/apt/keyrings/packages.microsoft.gpg != /usr/share/keyrings/microsoft.gpg, E:The list of sources could not be read."}
2025-06-22 15:57:51,318 p=45768 u=bill n=ansible INFO| fatal: [samsung]: FAILED! => {"changed": false, "msg": "E:Conflicting values set for option Signed-By regarding source https://packages.microsoft.com/repos/code/ stable: /etc/apt/keyrings/packages.microsoft.gpg != /usr/share/keyrings/microsoft.gpg, E:The list of sources could not be read."}
